version: '3'

networks:
  nuxt:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./docker/nginx/confs/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - node
    networks:
      - nuxt
    ports:
      - 8080:8080
  node:
    build:
      context: ./app
      dockerfile: ../docker/node/Dockerfile
    image: nuxt-app
    container_name: app
    restart: always
    user: "1000:1000"
    networks:
      - nuxt
    ports:
      - 3000:3000
