version: '3'

services:

  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
    image: for-me
    container_name: app
    hostname: wshof
#    user: "${UID}:${GID}"
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
#    entrypoint: npm i
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - node
    ports:
      - 8989:8989